### ISSUE TITLE
scale should probably be locked so people don't accidentally use it to bound the scene and get an error

### ISSUE THREAD

**Issue by spiraloid** [Powerbyte7/seurat_capture_addon#3]
bpy.context.object.lock_scale[0] = True
bpy.context.object.lock_scale[1] = True
bpy.context.object.lock_scale[2] = True

**Comment by Powerbyte7** [comment]
Good point, though being able to rescale the capturing box is an important part of the process. A bigger capture box will result in a larger viewable area for the user. The optimal solution would be a check to see if the box intersects with any meshes, but I'm not sure how to implement that.

**Comment by Powerbyte7** [comment]
Okay, I think it's possible to implement a rough check with raycasting, it wouldn't detect intersections in every case, but at least give an error when a user tries to bound the scene wit the box.

That should work something like this:

![image](https://user-images.githubusercontent.com/40431794/109285744-bb815000-7821-11eb-9cd6-72dfcf5fb38a.png)

**Comment by Powerbyte7** [comment]
I've implemented a basic check with 5494ebdeb26bb71a5971fa5863782339f6ec2060, it's not perfect because it only uses 18 rays, but it should work well enough for most cases. I'll look into refining it further later.

![image](https://user-images.githubusercontent.com/40431794/109310185-7fabb200-7844-11eb-98c3-e9c3f4b48dd5.png)

Thanks again for the feedback!
